version: '3.1'

services:
    node_api_testing:
        build:
            context: .
            dockerfile: docker/Dockerfile.testing
        container_name: node_api_testing
        restart: always
        #        env_file:
        #            - .environment/.testing.env
        environment:
            IS_TERMINATED: ${IS_TERMINATED}
            APP_ENV: ${APP_ENV}
            CPU_COUNT: ${CPU_COUNT}
            API_PORT: ${API_PORT}}
            DATABASE_URL: ${DATABASE_URL}
            SALT: ${SALT}
            JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
            JWT_ACCESS_EXPIRES_IN: ${JWT_ACCESS_EXPIRES_IN}
            JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
            JWT_REFRESH_EXPIRES_IN: ${JWT_REFRESH_EXPIRES_IN}
            JWT_ALGORITHM: ${JWT_ALGORITHM}
            COOKIES_JWT_REFRESH_TOKEN_EXP: ${COOKIES_JWT_REFRESH_TOKEN_EXP}
            LOG_LEVEL: ${LOG_LEVEL}
            LOAD_TEST_URL: ${LOAD_TEST_URL}
            NODE_ENV: ${NODE_ENV}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
        depends_on:
            - node_api_postgres_testing
        volumes:
            - ./:/usr/src/app
        networks:
            - node_api_testing_network

    node_api_postgres_testing:
        image: postgres:13.3-alpine
        container_name: node_api_postgres_testing
        restart: always
        logging:
            driver: none
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - pgdata_testing:/var/lib/postgresql/data
        networks:
            - node_api_testing_network

#  node_api_rmq_testing:
#    image: rabbitmq:3-management
#    container_name: node_api_rmq_testing
#    restart: always
#    logging:
#      driver: none
#    environment:
#      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
#      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
#    ports:
#      - 15672:15672
#      - 5672:5672
#    volumes:
#      - rabbitmq_data_testing:/var/lib/rabbitmq
#      - rabbitmq_log_testing:/var/log/rabbitmq
#    networks:
#      - node_api_testing_network

networks:
    node_api_testing_network:

volumes:
    pgdata_testing:
    rabbitmq_data_testing:
    rabbitmq_log_testing:
