export enum APP_ENV {
    LOCAL = 'local',
    DEVELOPMENT = 'development',
    STAGING = 'staging',
    PRODUCTION = 'production',
    TESTING = 'testing',
    LOAD_TESTING = 'load_testing',
}

export enum ENV_VARS {
    IS_TERMINATED = 'IS_TERMINATED',
    APP_ENV = 'APP_ENV',
    LOG_LEVEL = 'LOG_LEVEL',
    CPU_COUNT = 'CPU_COUNT',
    API_PORT = 'API_PORT',
    DATABASE_URL = 'DATABASE_URL',
    SALT = 'SALT',
    JWT_ACCESS_SECRET = 'JWT_ACCESS_SECRET',
    JWT_ACCESS_EXPIRES_IN = 'JWT_ACCESS_EXPIRES_IN',
    JWT_REFRESH_SECRET = 'JWT_REFRESH_SECRET',
    JWT_REFRESH_EXPIRES_IN = 'JWT_REFRESH_EXPIRES_IN',
    JWT_ALGORITHM = 'JWT_ALGORITHM',
    COOKIES_JWT_REFRESH_TOKEN_EXP = 'COOKIES_JWT_REFRESH_TOKEN_EXP',
}
