FROM node:18.12.1 AS prepare

WORKDIR /usr/src/app

COPY package*.json ./
COPY tsconfig*.json ./
COPY ./src ./src

RUN npm i -g typescript

FROM prepare AS builder

RUN npm ci && tsc

FROM node:18.12.1 as production

WORKDIR /app

COPY package*.json ./

COPY ./src/database/prisma/ ./src/database/prisma/

RUN npm ci --omit=dev && npx prisma generate

COPY --from=builder /usr/src/app/dist ./dist

USER node
