FROM node:18-alpine

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

RUN npm i -g npm@latest

COPY --chown=node:node . /usr/src/app

RUN npm ci

RUN npm run build

USER node

EXPOSE 8000/tcp

CMD node -r module-alias/register ./dist/main.js
