FROM node:18.12.1 as build

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

RUN npm i -g nodemon ts-node typescript

FROM build as local

COPY --chown=node:node . /usr/src/app

RUN npm ci && npx prisma generate

USER node
