name: Check
on: push
jobs:
    lint:
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install deps
              run: npm ci
            - name: Lint
              run: npm run lint
    test:
        runs-on: self-hosted
        needs: [lint]
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install deps
              run: npm ci
            - name: Test
              run: npx jest
    test-e2e:
        environment: testing
        runs-on: self-hosted
        needs: [lint, test]
        env:
            IS_TERMINATED: ${{ vars.IS_TERMINATED }}
            CPU_COUNT: ${{ vars.CPU_COUNT }}
            APP_ENV: ${{ vars.APP_ENV }}
            NODE_ENV: ${{ vars.NODE_ENV }}
            API_PORT: ${{ vars.API_PORT }}
            SALT: ${{ vars.SALT }}
            JWT_ACCESS_SECRET: ${{ vars.JWT_ACCESS_SECRET }}
            JWT_ACCESS_EXPIRES_IN: ${{ vars.JWT_ACCESS_EXPIRES_IN }}
            JWT_REFRESH_SECRET: ${{ vars.JWT_REFRESH_SECRET }}
            JWT_REFRESH_EXPIRES_IN: ${{ vars.JWT_REFRESH_EXPIRES_IN }}
            JWT_ALGORITHM: ${{ vars.JWT_ALGORITHM }}
            COOKIES_JWT_REFRESH_TOKEN_EXP: ${{ vars.COOKIES_JWT_REFRESH_TOKEN_EXP }}
            LOG_LEVEL: ${{ vars.LOG_LEVEL }}
            POSTGRES_USER: ${{ vars.POSTGRES_USER }}
            POSTGRES_PASSWORD: ${{ vars.POSTGRES_PASSWORD }}
            POSTGRES_DB: ${{ vars.POSTGRES_DB }}
            DATABASE_URL: ${{ vars.DATABASE_URL }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Build
              run: docker-compose -f docker-compose-testing.yaml build
            - name: Up -d
              run: docker-compose -f docker-compose-testing.yaml up -d --remove-orphans
            - name: Migrate
              run: docker-compose -f docker-compose-testing.yaml run -T node_api_testing npx prisma migrate reset --force
            - name: Test e2e
              run: docker-compose -f docker-compose-testing.yaml run node_api_testing npx jest --config jest.e2e.config.ts
            - name: Down
              run: docker-compose -f docker-compose-testing.yaml down --remove-orphans
