name: Check
on: push
jobs:
    lint:
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install deps
              run: npm ci

            - name: Lint
              run: npm run lint

    test-e2e:
        runs-on: self-hosted
        #        needs: [lint]
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Tests
              env:
                  DATABASE_URL: ${{ vars.DATABASE_URL }}
              #                  DATABASE_URL: ${{ secrets.DATABASE_URL }}
              run: |
                  docker-compose -f docker-compose-testing.yaml build
