name: Check
on: push
jobs:
    lint:
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install deps
              run: npm ci

            - name: Lint
              run: npm run lint

    test-e2e:
        runs-on: self-hosted
        #        needs: [lint]
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Tests
              env:
                  IS_TERMINATED: ${{ secrets.IS_TERMINATED }}
                  APP_ENV: ${{ secrets.APP_ENV }}
                  CPU_COUNT: ${{ secrets.CPU_COUNT }}
                  API_PORT: ${{ secrets.API_PORT }}
                  DATABASE_URL: ${{ secrets.DATABASE_URL }}
                  SALT: ${{ secrets.SALT }}
                  JWT_ACCESS_SECRET: ${{ secrets.JWT_ACCESS_SECRET }}
                  JWT_ACCESS_EXPIRES_IN: ${{ secrets.JWT_ACCESS_EXPIRES_IN }}
                  JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
                  JWT_REFRESH_EXPIRES_IN: ${{ secrets.JWT_REFRESH_EXPIRES_IN }}
                  JWT_ALGORITHM: ${{ secrets.JWT_ALGORITHM }}
                  COOKIES_JWT_REFRESH_TOKEN_EXP: ${{ secrets.COOKIES_JWT_REFRESH_TOKEN_EXP }}
                  LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
                  LOAD_TEST_URL: ${{ secrets.LOAD_TEST_URL }}
                  NODE_ENV: ${{ secrets.NODE_ENV }}
                  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
                  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
                  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
                  RABBITMQ_DEFAULT_PASS: ${{ secrets.RABBITMQ_DEFAULT_PASS }}
                  RABBITMQ_DEFAULT_USER: ${{ secrets.RABBITMQ_DEFAULT_USER }}
              run: |
                  docker-compose -f docker-compose-testing.yaml build
                  docker-compose -f docker-compose-testing.yaml up -d --remove-orphans
                  docker-compose -f docker-compose-testing.yaml run -T node_api_testing npx prisma migrate dev
                  docker-compose -f docker-compose-testing.yaml run node_api_testing npx jest --config jest.e2e.config.ts
