name: Check
on: push
jobs:
    lint:
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install deps
              run: npm ci

            - name: Lint
              run: npm run lint

    test-e2e:
        runs-on: self-hosted
        #        needs: [lint]
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up Docker Compose
              run: |
                  export $(cat .environment/.testing.env | xargs)
                  echo "POSTGRES_USER=$POSTGRES_USER" >> $GITHUB_ENV
                  echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> $GITHUB_ENV
                  echo "POSTGRES_DB=$POSTGRES_DB" >> $GITHUB_ENV

            - name: Tests
              uses: cloudposse/github-action-docker-compose-test-run@main
              with:
                  file: docker-compose-testing.yaml
                  command: |
                      docker-compose -f docker-compose-testing.yaml build
                      docker-compose -f docker-compose-testing.yaml up -d --remove-orphans
                      docker-compose -f docker-compose-testing.yaml run -T node_api_testing npx prisma migrate dev
                      docker-compose -f docker-compose-testing.yaml run node_api_testing npx jest --config jest.e2e.config.ts
